platform :ios, '9.3'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SumSubstance/Specs.git'

use_frameworks!

target 'Sumsubstance' do

  pod 'SumSubstanceKYC'

  # any other dependencies
end